### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by lucas-a-pelegrino** [lucas-a-pelegrino/node-bloodboiler-sequelized#20]
**Description**
The application should have a CI build setup. Using [Github Actions](https://github.com/features/actions) to run the scripts.

**Additional Context**
The _build script_ should run `npm install` and `npm test` commands, then send code coverage report to **Codecov**, **Codacy** will review the code on every merge made to the _**develop** and **master** branch_.

**Tasks**
- [x] Write Unit/Integration Tests
- [x] Integrate Project with Codecov
- [x] Integrate Project with Codacy
